name: shoe_spotter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.4+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  # State management
  flutter_bloc: ^8.1.4
  # Equatable for state management and equality checking
  equatable: ^2.0.5
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^7.6.7
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Utility Packages
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  # Icons
  iconsax: ^0.0.8
  # Product Specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  get: ^4.6.6
  connectivity_plus: ^6.0.1

  # Local Storage
  get_storage: ^2.1.1
  # Firebase
  firebase_storage: ^11.5.5
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  lottie: ^3.1.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
