// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmS_XPZMaxZmSAGDRY3xobR_2fdHVN4G8',
    appId: '1:921117579238:web:20b4cbbf99190fa28f2827',
    messagingSenderId: '921117579238',
    projectId: 'tshoe-spotter-flutter',
    authDomain: 'tshoe-spotter-flutter.firebaseapp.com',
    storageBucket: 'tshoe-spotter-flutter.appspot.com',
    measurementId: 'G-Z0S4CJZPCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR8xSqxmt6m2hQ1ZVIw4bM51jkPe-UGCg',
    appId: '1:921117579238:android:ad43098cb093674c8f2827',
    messagingSenderId: '921117579238',
    projectId: 'tshoe-spotter-flutter',
    storageBucket: 'tshoe-spotter-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdL5waBqB_lOrr2BPV2n3xCvHEy3J53rg',
    appId: '1:921117579238:ios:e27fa5e0f0f1f3bf8f2827',
    messagingSenderId: '921117579238',
    projectId: 'tshoe-spotter-flutter',
    storageBucket: 'tshoe-spotter-flutter.appspot.com',
    iosBundleId: 'com.example.shoeSpotter',
  );

}