// ignore_for_file: constant_identifier_names

class FirebaseConst {
  static const String USERS_COLLECTION = "USERS_COLLECTION";
  static const String PATH_IMAGE_USER_COLLECTION = "Users/Images/Profile/";
  static const String PATH_IMAGE_CATEGORY_COLLECTION = "Categories";
  static const String ORDERS_COLLECTION = "ORDERS_COLLECTION";
  static const String PRODUCTS_COLLECTION = "PRODUCTS_COLLECTION";
  static const String CART_COLLECTION = "CART_COLLECTION";
  static const String CATEGORIES_COLLECTION = "CATEGORIES_COLLECTION";
  static const String SUBCATEGORIES_COLLECTION = "SUBCATEGORIES_COLLECTION";
  static const String REVIEWS_COLLECTION = "REVIEWS_COLLECTION";
  static const String SHOPS_COLLECTION = "SHOPS_COLLECTION";
  static const String NOTIFICATIONS_COLLECTION = "NOTIFICATIONS_COLLECTION";
  static const String ADDRESS_COLLECTION = "ADDRESS_COLLECTION";
  static const String SHIPPING_ADDRESS_COLLECTION = "SHIPPING_ADDRESS_COLLECTION";
  static const String PAYMENT_METHOD_COLLECTION = "PAYMENT_METHOD_COLLECTION";
  static const String SHIPPING_METHOD_COLLECTION = "SHIPPING_METHOD_COLLECTION";
}

class AppPrefsKeys {
  // Keys
  static const String PREFS_KEY_LANG = "PREFS_KEY_LANG";
  static const String PREFS_KEY_ONBOARDING_SCREEN_VIEWED =
      "PREFS_KEY_ONBOARDING_SCREEN_VIEWED";
  static const String PREFS_KEY_IS_USER_LOGGED_IN =
      "PREFS_KEY_IS_USER_LOGGED_IN";
  static const String PREFS_KEY_REMEMBER_ME_EMAIL =
      "PREFS_KEY_REMEMBER_ME_EMAIL";
  static const String PREFS_KEY_REMEMBER_ME_PASSWORD =
      "PREFS_KEY_REMEMBER_ME_PASSWORD";
}
