default_platform(:android)

platform :android do
  desc "Lane for Android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons" 
    firebase_app_distribution(
    app: "1:921117579238:android:ad43098cb093674c8f2827",
    firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type:"APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers:"osamaerhy32@gmail.com",
    release_notes:"Testing something with GitHub Actions, trying to push directly to firebase distribution",
  )
  end
end
